# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- release

jobs:
- job: buildandtest

  pool:
    vmImage: ubuntu-latest

  variables:
    buildConfiguration: 'release'

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages - dotnet restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
    
  - task: DotNetCoreCLI@2
    displayName: Build the project - dotnet build $(buildConfiguration)
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Publish the output from project - dotnet publish
    inputs:
      command: publish
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'Nexus.Auth'
